### ISSUE TITLE
CosmosDataSource requires Context now?

### ISSUE THREAD

**Issue by diberry** [andrejpk/apollo-datasource-cosmosdb#73]
Can you update the sample code to explain where the `ApolloContext` is from (package) and how it is created? 

```
export class UserDataSource extends CosmosDataSource<UserDoc, ApolloContext> {}
```

I'm updating from 0.0.14 where it wasn't required to 0.1.0 where it seems to be required.

**Comment by diberry** [comment]
Ok, here is what I did to get past the Type Error but honestly not sure why the ApolloContext is listed in the docs and then why I don't really need it. 

Changed

```
export class GameDataSource
  extends CosmosDataSource<GameModel, ApolloContext>
  implements IGameDataSource
{
```
to

```
export class GameDataSource
  extends CosmosDataSource<GameModel, any>
  implements IGameDataSource
{
```

**Comment by andrejpk** [comment]
sorry missed the notifications and got behind here. 

The context is a type parameter so you can use an enriched type for ApolloContext. I'll add something to the docs on this.
